version: '3.9'

services:
  watchtower: # done
    container_name: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3011:8080
    networks:
      - treafik_proxy
    command: --http-api-metrics --debug prometheus grafana
    restart: unless-stopped
  prometheus: # done
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 3010:9090
    networks:
      - treafik_proxy
    restart: unless-stopped
  grafana: # done
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - treafik_proxy
    restart: unless-stopped
  filebrowser: # done
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    ports:
      - 3002:80
    volumes:
      - /home/zeroring:/srv
      - ./configs/filebrowser.json:/config/settings.json
      # - /portainer/Files/AppData/Config/filebrowser/filebrowser.db:/database/filebrowser.db
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
    restart: unless-stopped
  pihole: # done
    container_name: pihole
    image: cbcrowe/pihole-unbound:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 4443:443
      - 3001:80
    networks:
      - treafik_proxy
    # volumes:
    #   - /portainer/Files/AppData/Config/PiHole-Unbound/DNS:/etc/dnsmasq.d
    #   - /portainer/Files/AppData/Config/PiHole-Unbound:/etc/pihole
    environment:
      - ServerIP=192.168.0.106
      - TZ=Europe\Kiev
      - DNSSEC=true
      - DNS1=127.0.0.1#5335
      - DNS2=127.0.0.1#5335
      - PIHOLE_DNS_=127.0.0.1#5335
      - WEBPASSWORD=admin
      - WEBTHEME=default-dark
      - S6_OVERLAY_VERSION=v2.1.0.2
      - IPv6=True
      - S6_LOGGING=0
      - S6_KEEP_ENV=1
      - S6_BEHAVIOUR_IF_STAGE2_FAILS=2
      - FTL_CMD=no-daemon
      - DNSMASQ_USER=pihole
      # - PATH=/opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      # - phpver=php
      # - PIHOLE_DOCKER_TAG=2022.05
      # - PIHOLE_INSTALL=/etc/.pihole/automated install/basic-install.sh
      # - PHP_ENV_CONFIG=/etc/lighttpd/conf-enabled/15-fastcgi-php.conf
      # - PHP_ERROR_LOG=/var/log/lighttpd/error.log
    restart: unless-stopped
  nodeexporter: # done
    container_name: node_exporter
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
    networks:
      - treafik_proxy
    command: --path.rootfs=/host
    volumes:
      - /:/host:ro
    restart: unless-stopped
  cadvisor: # done
    container_name: cadvisor
    image: zcube/cadvisor:latest
    ports:
      - 8083:8080
    volumes:
      - /dev/disk:/dev/disk:ro
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run:/var/run:ro
    networks:
      - treafik_proxy
    environment:
      - CADVISOR_HEALTHCHECK_URL=http://localhost:8080/healthz
    restart: unless-stopped

# volumes:
#   prometheus: {}

networks:
  treafik_proxy: {}