version: '3.9'

services:
  filebrowser: # done
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    # ports:
    #   - 3002:80
    volumes:
      - /home/zeroring:/srv
      - ./configs/filebrowser.json:/config/settings.json
      # - /portainer/Files/AppData/Config/filebrowser/filebrowser.db:/database/filebrowser.db
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
    restart: unless-stopped

networks:
  treafik_proxy:
    driver: bridge
    external: true