version: '3.9'

services:
  filebrowser: # done
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    ports:
      - 3002:80
    networks:
      - treafik_proxy
    volumes:
      - /home/zeroring:/srv
      - ./configs/filebrowser/filebrowser.json:/.filebrowser.json:rw
      - ./configs/filebrowser/filebrowser.db:/database.db:rw
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

networks:
  treafik_proxy:
    driver: bridge
    external: true