version: '3.9'

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    # ports:
    #   - 3002:80
    networks:
      - treafik_proxy
    volumes:
      - /home/zeroring:/srv
      - ./configs/filebrowser/filebrowser.json:/.filebrowser.json:rw
      - ./configs/filebrowser/filebrowser.db:/database.db:rw
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser-req.rule=Host(`files.oholvitalii.com`) || Host(`files.berry`)"
      - "traefik.http.routers.filebrowser-req.entryPoints=http"
      - "traefik.http.routers.filebrowser-req.middlewares=b-auth@file"
      - "traefik.http.services.filebrowser.loadbalancer.passHostHeader=true"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
    restart: unless-stopped

networks:
  treafik_proxy:
    driver: bridge
    external: true
