version: '3.9'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - mdb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=zeroring
      - MYSQL_ROOT_PASSWORD=8Aps6WmY
      - MYSQL_PASSWORD=8Aps6WmY
    networks:
      - treafik_proxy
    restart: unless-stopped

volumes:
  mdb: { }

networks:
  treafik_proxy:
    driver: bridge
    external: true
