version: '3.9'

services:
  pihole:
    container_name: pihole
    image: cbcrowe/pihole-unbound:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      # - 4443:443
      # - 3001:80
    networks:
      - treafik_proxy
    volumes:
      - ./configs/resolv.conf:/etc/resolv.conf:ro
      - etcd:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    environment:
      - FTLCONF_REPLY_ADDR4=192.168.0.106
      - TZ=Europe\Kiev
      - PIHOLE_DNS_=127.0.0.1#5335;127.0.0.1#5335
      - WEBPASSWORD=franki
      - WEBTHEME=default-dark
      - CUSTOM_CACHE_SIZE=10000
      - WEBUIBOXEDLAYOUT=traditional
      - TEMPERATUREUNIT=c
      - QUERY_LOGGING=true
      - DNSSEC=false
      # - REV_SERVER=true
      # - DNSMASQ_USER=pihole
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.pihole.rule=PathPrefix(`/hole/admin`)"
      - "traefik.http.routers.pihole.entryPoints=https"
      - "traefik.http.routers.pihole.middlewares=pihole-strip"

      - "traefik.http.routers.pihole-redr.rule=Path(`/hole`, `/admin`, `/hole/`, `/admin/`)"
      - "traefik.http.routers.pihole-redr.entryPoints=https"
      - "traefik.http.routers.pihole-redr.middlewares=pihole-redirect"

      - "traefik.http.services.pihole.loadbalancer.passHostHeader=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

      - "traefik.http.middlewares.pihole-strip.stripprefix.prefixes=/hole"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.regex=^https?://(.+?)/(?:hole|admin)(?:/(.*))?"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.replacement=https://$${1}/hole/admin/$${2}"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.permanent=true"
      # - "traefik.http.middlewares.pi-chain.chain.middlewares=pihole-strip,pihole-add,tmp-strip"
    restart: unless-stopped

volumes:
  etcd:
    driver: local
  dnsmasq:
    driver: local

networks:
  treafik_proxy:
    driver: bridge
    external: true
