version: '3.9'

services:
  portainer:
    container_name: portainer
    image: 'portainer/portainer-ce:latest'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - 9000:9000
      - 9443:9443
      - 8000:8000
    # networks:
    #   - treafik_proxy
    restart: unless-stopped

volumes:
  portainer-data:
    driver: local