version: '3.9'

services:
  prometheus: # done
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    # ports:
    #   - 3010:9090
    networks:
      - treafik_proxy
    restart: unless-stopped

networks:
  treafik_proxy:
    driver: bridge
    external: true