version: '3.9'

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./configs/traefik/:/etc/traefik/
    networks:
      - treafik_proxy
    labels:
      traefik.http.routers.api.rule: Host(`zeroring.duckdns.org`)    # Define the subdomain for the traefik dashboard.
      traefik.http.routers.api.entryPoints: https    # Set the Traefik entry point.
      traefik.http.routers.api.service: api@internal    # Enable Traefik API.
      traefik.enable: true   # Enable Traefik reverse proxy for the Traefik dashboard.
    restart: unless-stopped

networks:
  treafik_proxy:
    driver: bridge
    external: true