global:
  checkNewVersion: true
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

# Log level INFO|DEBUG|ERROR
log:
  level: INFO

api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
    http:
      tls:
        certResolver: staging
        domains:
          - main: zeroring.duckdns.org
            sans:
              - '*.zeroring.duckdns.org'
      middlewares:
        - securityHeaders@file

providers:
  providersThrottleDuration: 2s
  file:
    filename: /etc/traefik/fileConfig.yml
    watch: true
  docker:
    watch: true
    network: treafik_proxy
    defaultRule: "Host(`zeroring.duckdns.org/{{ index .Labels \"com.docker.compose.service\"}}`)"
    swarmModeRefreshSeconds: 15s
    exposedByDefault: false

# Use letsencrypt to generate ssl serficiates
certificatesResolvers:
  staging:
    acme:
      email: ohol.vitaliy@gmail.com
      storage: /etc/traefik/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: http
  production:
    acme:
      email: ohol.vitaliy@gmail.com
      storage: /etc/traefik/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: http
