global:
  scrape_interval: 1m
  scrape_timeout: 20s

scrape_configs:
  - job_name: 'monitoring'
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets: 
        - 'localhost:9090' # prometheus
        - 'cadvisor:8080' # cadvisor
        - 'node_exporter:9100' # node exporter